import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  integer,
  pgTable,
  serial,
  text,
  time,
  timestamp,
  unique,
  varchar,
} from "drizzle-orm/pg-core";

// Better Auth tables (generated by @better-auth/cli).
export * from "./auth-schema";

/**
 * Shared contract with the executor (docs/M1-SPEC.md): app-owned zone config.
 * id is the controller station id (1..7). The executor reads this table to
 * refuse starts of disabled zones.
 */
export const zones = pgTable("zones", {
  id: integer("id").primaryKey(),
  name: varchar("name", { length: 40 }).notNull(),
  enabled: boolean("enabled").notNull().default(true),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type ZoneConfig = typeof zones.$inferSelect;

/**
 * M2 shared contract (docs/M2-SPEC.md): app-owned scheduling.
 * web-next owns these tables and their migrations; the executor reads
 * programs/program_steps, claims run_requests, and writes program_runs /
 * program_run_steps. All start times are LOCAL wall times in the executor's
 * SCHEDULE_TIMEZONE.
 */

export const programs = pgTable(
  "programs",
  {
    id: serial("id").primaryKey(),
    name: varchar("name", { length: 60 }).notNull(),
    enabled: boolean("enabled").notNull().default(true),
    /** Local wall times, >=1 entry. */
    startTimes: time("start_times").array().notNull(),
    dayType: text("day_type").notNull(),
    /** 0=Mon .. 6=Sun, required iff day_type = 'days_of_week'. */
    daysOfWeek: integer("days_of_week").array(),
    /** >=1, required iff day_type = 'interval'. */
    intervalDays: integer("interval_days"),
    /** Required iff day_type = 'interval'. */
    anchorDate: date("anchor_date"),
    respectRainDelay: boolean("respect_rain_delay").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      "programs_day_type_check",
      sql`${t.dayType} IN ('days_of_week','interval')`,
    ),
  ],
);

export const programSteps = pgTable(
  "program_steps",
  {
    id: serial("id").primaryKey(),
    programId: integer("program_id")
      .notNull()
      .references(() => programs.id, { onDelete: "cascade" }),
    /** 0-based, contiguous. */
    position: integer("position").notNull(),
    zoneId: integer("zone_id")
      .notNull()
      .references(() => zones.id),
    minutes: integer("minutes").notNull(),
  },
  (t) => [
    unique("program_steps_program_id_position_unique").on(
      t.programId,
      t.position,
    ),
    check(
      "program_steps_minutes_check",
      sql`${t.minutes} BETWEEN 1 AND 240`,
    ),
  ],
);

/** "Run now": web writes, executor claims. */
export const runRequests = pgTable("run_requests", {
  id: serial("id").primaryKey(),
  programId: integer("program_id")
    .notNull()
    .references(() => programs.id, { onDelete: "cascade" }),
  /** User email. */
  requestedBy: text("requested_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  /** Set by the executor. */
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
});

/** History: executor writes, web reads. */
export const programRuns = pgTable(
  "program_runs",
  {
    id: serial("id").primaryKey(),
    programId: integer("program_id").references(() => programs.id, {
      onDelete: "set null",
    }),
    /** Denormalized, survives program deletes. */
    programName: varchar("program_name", { length: 60 }).notNull(),
    /** Null for run-now. */
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }),
    /** 'schedule' | user email. */
    initiator: text("initiator").notNull(),
    status: text("status").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    note: text("note"),
  },
  (t) => [
    check(
      "program_runs_status_check",
      sql`${t.status} IN ('running','completed','partial','failed','cancelled','skipped_rain_delay','missed')`,
    ),
  ],
);

export const programRunSteps = pgTable(
  "program_run_steps",
  {
    id: serial("id").primaryKey(),
    runId: integer("run_id")
      .notNull()
      .references(() => programRuns.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    zoneId: integer("zone_id").notNull(),
    /** Denormalized. */
    zoneName: varchar("zone_name", { length: 40 }).notNull(),
    plannedMinutes: integer("planned_minutes").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    outcome: text("outcome"),
  },
  (t) => [
    check(
      "program_run_steps_outcome_check",
      sql`${t.outcome} IN ('completed','cancelled','failed','skipped_disabled')`,
    ),
  ],
);

export type Program = typeof programs.$inferSelect;
export type ProgramStep = typeof programSteps.$inferSelect;
export type ProgramRun = typeof programRuns.$inferSelect;
export type ProgramRunStep = typeof programRunSteps.$inferSelect;
